language: java
jdk:
  - openjdk11

branches:
  only:
    - main

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_deploy:
  - zip -r travis-test *
  - mkdir -p deploy
  - mv travis-test.zip deploy/travis-test.zip

deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY  # Travis repo에 설정한 값.
  secret_access_key: $AWS_SECRET_KEY
  bucket: idol-collector-build
  region: ap-northeast-2
  acl: private  # zip 파일 접근 private
  local_dir: deploy  # befroe_deploy에서 생성한 폴더




# CI 실행 완료 시 메일로 알람
notifications:
  email:
    recipients:
      - totw5701@naver.com